server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  application:
    name: serie-service
  data:
    mongodb:
      database: serie-dev
      authentication-database: admin
      authSource: admin
      port: 27017
      host: localhost
      username: usr-series
      password: pwd-series
  zipkin:
    baseUrl: http://localhost:9411/
  eureka:
    client:
      registerWithEureka: true
      fetchRegistry: true
      service-url:
        defaultZone: http://localhost:8761/eureka
    instance:
      hostname: localhost
      instance-id: ${spring.application.name}:${spring.application.instance-id:${random.value}}