server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  application:
    name: catalog-service
  zipkin:
    baseUrl: http://localhost:9411/
  data:
    mongodb:
      database: catalog-dev
      port: 27018
      authentication-database: admin
      authSource: admin
      host: localhost
      username: usr-catalog
      password: pwd-catalog
  eureka:
    client:
      registerWithEureka: true
      fetchRegistry: true
      service-url:
        defaultZone: http://localhost:8761/eureka
    instance:
      hostname: localhost
      instance-id: ${spring.application.name}:${spring.application.instance-id:${random.value}}
resilience4j:
  retry:
    configs:
      default:
        max-retry-attempts: 3
        wait-duration: 1s
        retry-exceptions:
          - java.io.IOException
          - java.net.SocketTimeoutException
      instances:
        catalog:
          base-config: default
          max-retry-attempts: 5
          wait-duration: 2s
          retry-exceptions:
            - java.net.ConnectException
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        wait-duration-in-open-state: 30s
        automatic-transition-from-open-to-half-open-enabled: true
        failure-rate-threshold: 40
    instances:
      catalog:
        base-config: default
        sliding-window-type: COUNT_BASED
        sliding-window-size: 5
        wait-duration-in-open-state: 1m
        failure-rate-threshold: 50